image:
  - macOS

platform:
  - x64
  - x86

branches:
  only:
    - master

build:
  verbosity: detailed

configuration:
  - Release
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)

for:
  -
    matrix:
      only:
        - image: macOS
  
    install:
     - git submodule update --init --recursive
     - brew install qt5
     - export PATH="/usr/local/opt/qt/bin:$PATH"
     - export LDFLAGS="-L/usr/local/opt/qt/lib"
     - export CPPFLAGS="-I/usr/local/opt/qt/include"
     - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

    before_build:
      - cmake --version
      - qmake -v
      - mkdir build
      - cd build

    build_script:
      - cmake ..
      - cmake --build . --target all

    after_build:
       - ls

    artifacts:
       - path: build
